# Enhanced Governance Pre-Commit Configuration
# Enforces three-persona validation before commits

repos:
  # Python code quality
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/pycqa/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args: ['--max-line-length=100', '--ignore=E203,W503']

  # Security checks
  - repo: https://github.com/Yelp/detect-secrets
    rev: v1.4.0
    hooks:
      - id: detect-secrets
        args: ['--baseline', '.secrets.baseline']

  # Custom governance hooks
  - repo: local
    hooks:
      - id: governance-check
        name: Three-Persona Governance Validation
        entry: python governance_enforcer.py
        language: python
        pass_filenames: true
        always_run: true
        stages: [commit]
        
      - id: evidence-collection
        name: Automated Evidence Collection
        entry: python smart_evidence_collector.py
        language: python
        pass_filenames: true
        
      - id: assumption-detection
        name: AI Assumption Detection
        entry: python assumption_scanner.py
        language: python
        types: [python]
        
      - id: magic-variable-check
        name: Magic Variable Detection
        entry: python magic_variable_detector.py
        language: python
        types: [python, yaml, json]